/*
 * This source file was generated by the Gradle 'init' task
 */
package pigtracker;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class Main extends Application {

    @Override
    public void start(Stage stage) throws Exception {
        System.out.println(
            Main.class.getResource("/views/main-view.fxml")
        );

        FXMLLoader loader = new FXMLLoader(
                Main.class.getResource(
                        "/views/main-view.fxml"
                )
                );
                

        Scene scene = new Scene(loader.load());

        stage.setTitle("PigTracker");
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
