/*
 * This source file was generated by the Gradle 'init' task
 */
package pigtracker;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

public class Main extends Application {

    @Override
    public void start(Stage stage) {
        testJavaFX(stage);
    }

    public static void main(String[] args) {
        launch();
    }

    private void testJavaFX(Stage stage) {
        Button button = new Button("JavaFX works!");

        Scene scene = new Scene(button, 400, 200);

        stage.setTitle("PigTracker");
        stage.setScene(scene);
        stage.show();
    }
}
