/*
 * This source file was generated by the Gradle 'init' task
 */
package pigtracker;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

@SuppressWarnings("unused")
class AppTest {

}
